/**
 * @description       : Wrapper Class for StudentMarkCalc
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-09-2026
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class StudentData {
    public String name;
    public Integer physicsMark;
    public Integer chemistryMark;
    public Integer mathMark;
}
